### PR TITLE
Fixed button borders on webkit and upgraded styled dependencies

### PR DESCRIPTION
**Pull request by jsonmaur**
Default borders on webkit were not being normalized. Also upgraded `styled-components` and `styled-system` in an attempt to reduce issues.

### CODE REVIEW

**Comment by jsonmaur** [comment]
Also not sure why `package-lock.json` was committed alongside `yarn.lock`.

**Comment by zsherman** [comment]
@jsonmaur this will happen if you `npm install` as opposed to `yarn install`, should use yarn where possible.

**Comment by jsonmaur** [comment]
@zsherman Agreed, should probably add package-lock.json to the git ignore.

**Comment by zsherman** [comment]
Yep, for now I would.

**Pull request merged**
